/**
 * CODE = 0x{ERROR}{MENU}{SUB_MENU}{SEQ}
 *
 * ERROR = 1 / SUCCESS = 0
 *
 * MENU = 00 ~ FF
 *
 * SUB_MENU = 00 = FF
 *
 * SEQ = 01 ~ FF
 *
 * EX) RESPONSE_CODE.AUTH.GET_PROFILES_BODY_INVALID = 0x|1|01|03|01
 */
export const RESPONSE_CODE = {
	AUTH: {
		GET_PROFILES_BODY_INVALID: 0x1010301,
		GET_PROFILES_BODY_INVALID_EMAIL: 0x1010302,
		GET_PROFILES_BODY_INVALID_PASSWORD: 0x1010303,
		GET_PROFILES_UNMATCH_USER: 0x1010304,
		GET_PROFILES_SUCCESS: 0x010301,
	},
	SESSION: {},
	USER: {},
	PROFILE: {},
	FRIEND: {},
	DM: {
		GET_DM_PARTICIPANTS_SESSION_INVALID: 0x1050301,
		GET_DM_PARTICIPANTS_PARAMS_INVALID: 0x1050302,
		GET_DM_PARTICIPANTS_PARAMS_INVALID_DM_SESSION_ID: 0x1050303,
		GET_DM_PARTICIPANTS_DM_SESSION_NOT_FOUND: 0x1050304,
		GET_DM_PARTICIPANTS_DM_SESSION_NOT_JOIN: 0x1050305,
		GET_DM_PARTICIPANTS_SUCCESS: 0x0050301,
		CREATE_DM_PARTICIPANT_SESSION_INVALID: 0x1050701,
		CREATE_DM_PARTICIPANT_PARAMS_INVALID: 0x1050702,
		CREATE_DM_PARTICIPANT_PARAMS_INVALID_DM_SESSION_ID: 0x1050703,
		CREATE_DM_PARTICIPANT_BODY_INVALID: 0x1050704,
		CREATE_DM_PARTICIPANT_BODY_INVALID_PROFILE_ID: 0x1050705,
		CREATE_DM_PARTICIPANT_DM_SESSION_NOT_FOUND: 0x1050706,
		CREATE_DM_PARTICIPANT_DM_SESSION_NOT_JOIN: 0x1050707,
		CREATE_DM_PARTICIPANT_PROFILE_NOT_FOUND: 0x1050706,
		CREATE_DM_PARTICIPANT_SUCCESS: 0x0050701,
		DELETE_DM_PARTICIPANT_SESSION_INVALID: 0x1050401,
		DELETE_DM_PARTICIPANT_PARAMS_INVALID: 0x1050402,
		DELETE_DM_PARTICIPANT_PARAMS_INVALID_DM_SESSION_ID: 0x1050403,
		DELETE_DM_PARTICIPANT_PARAMS_INVALID_PROFILE_ID: 0x1050404,
		DELETE_DM_PARTICIPANT_DM_SESSION_NOT_FOUND: 0x1050405,
		DELETE_DM_PARTICIPANT_DM_SESSION_NOT_JOIN: 0x1050406,
		DELETE_DM_PARTICIPANT_ALREADY_PARTICIPANT: 0x1050407,
		DELETE_DM_PARTICIPANT_SUCCESS: 0x0050401,
		CREATE_DM_MESSAGE_SESSION_INVALID: 0x1050101,
		CREATE_DM_MESSAGE_PARAMS_INVALID: 0x1050102,
		CREATE_DM_MESSAGE_PARAMS_INVALID_DM_SESSION_ID: 0x1050103,
		CREATE_DM_MESSAGE_BODY_INVALID: 0x1050104,
		CREATE_DM_MESSAGE_BODY_INVALID_MESSAGE: 0x1050105,
		CREATE_DM_MESSAGE_DM_SESSION_NOT_FOUND: 0x1050106,
		CREATE_DM_MESSAGE_DM_SESSION_NOT_JOIN: 0x1050107,
		CREATE_DM_MESSAGE_SUCCESS: 0x0050101,
	},
	ROOM: {},
	API: {},
	BAD_REQUEST: 0x00001,
	UNAUTHORIZED: 0x00002,
	INTERNAL_SERVER_ERROR: 0x00003,
} as const

export type RESPONSE_CODE_AUTH_GET_PROFILES_BODY_INVALID =
	| typeof RESPONSE_CODE.AUTH.GET_PROFILES_BODY_INVALID
	| typeof RESPONSE_CODE.AUTH.GET_PROFILES_BODY_INVALID_EMAIL
	| typeof RESPONSE_CODE.AUTH.GET_PROFILES_BODY_INVALID_PASSWORD

export type RESPONSE_CODE_DM_CREATE_DM_MESSAGE_PARAMS_INVALID =
	| typeof RESPONSE_CODE.DM.CREATE_DM_MESSAGE_PARAMS_INVALID
	| typeof RESPONSE_CODE.DM.CREATE_DM_MESSAGE_PARAMS_INVALID_DM_SESSION_ID

export type RESPONSE_CODE_DM_CREATE_DM_MESSAGE_BODY_INVALID =
	| typeof RESPONSE_CODE.DM.CREATE_DM_MESSAGE_BODY_INVALID
	| typeof RESPONSE_CODE.DM.CREATE_DM_MESSAGE_BODY_INVALID_MESSAGE

export type RESPONSE_CODE_DM_DELETE_DM_PARTICIPANT_PARAMS =
	| typeof RESPONSE_CODE.DM.DELETE_DM_PARTICIPANT_PARAMS_INVALID
	| typeof RESPONSE_CODE.DM.DELETE_DM_PARTICIPANT_PARAMS_INVALID_DM_SESSION_ID
	| typeof RESPONSE_CODE.DM.DELETE_DM_PARTICIPANT_PARAMS_INVALID_PROFILE_ID

export type RESPONSE_CODE_DM_GET_DM_PARTICIPANTS_INVALID_PARAMS =
	| typeof RESPONSE_CODE.DM.GET_DM_PARTICIPANTS_PARAMS_INVALID
	| typeof RESPONSE_CODE.DM.GET_DM_PARTICIPANTS_PARAMS_INVALID_DM_SESSION_ID

export type RESPONSE_CODE_DM_CREATE_DM_PARTICIPANT_PARAMS_INVALID =
	| typeof RESPONSE_CODE.DM.CREATE_DM_PARTICIPANT_PARAMS_INVALID
	| typeof RESPONSE_CODE.DM.CREATE_DM_PARTICIPANT_PARAMS_INVALID_DM_SESSION_ID

export type RESPONSE_CODE_DM_CREATE_DM_PARTICIPANT_BODY_INVALID =
	| typeof RESPONSE_CODE.DM.CREATE_DM_PARTICIPANT_BODY_INVALID
	| typeof RESPONSE_CODE.DM.CREATE_DM_PARTICIPANT_BODY_INVALID_PROFILE_ID
