/*
  Warnings:

  - The primary key for the `deleted_profile` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `dm_message` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `dm_participant` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `filter_user` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `friend` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `friend_request` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `profile` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `room_channel` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `room_join_code` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `room_message` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `room_participant` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `user` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `user_profile_status` table will be changed. If it partially fails, the table could be left without primary key constraint.

*/
-- DropForeignKey
ALTER TABLE "dm_message" DROP CONSTRAINT "dm_message_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "dm_participant" DROP CONSTRAINT "dm_participant_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "filter_user" DROP CONSTRAINT "filter_user_filter_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "filter_user" DROP CONSTRAINT "filter_user_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "friend" DROP CONSTRAINT "friend_friend_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "friend" DROP CONSTRAINT "friend_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "friend_request" DROP CONSTRAINT "friend_request_friend_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "friend_request" DROP CONSTRAINT "friend_request_user_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "profile" DROP CONSTRAINT "profile_user_id_fkey";

-- DropForeignKey
ALTER TABLE "room" DROP CONSTRAINT "room_master_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "room_join_code" DROP CONSTRAINT "room_join_code_author_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "room_message" DROP CONSTRAINT "room_message_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "room_message" DROP CONSTRAINT "room_message_room_channel_id_fkey";

-- DropForeignKey
ALTER TABLE "room_participant" DROP CONSTRAINT "room_participant_user_profile_id_fkey";

-- DropForeignKey
ALTER TABLE "user_profile_status" DROP CONSTRAINT "user_profile_status_user_id_fkey";

-- AlterTable
ALTER TABLE "deleted_profile" DROP CONSTRAINT "deleted_profile_pkey",
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "user_id" SET DATA TYPE BIGINT,
ALTER COLUMN "status_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "deleted_profile_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "dm_message" DROP CONSTRAINT "dm_message_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "dm_message_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "dm_participant" DROP CONSTRAINT "dm_participant_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "dm_participant_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "filter_user" DROP CONSTRAINT "filter_user_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "filter_profile_id" SET DATA TYPE BIGINT,
ALTER COLUMN "profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "filter_user_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "friend" DROP CONSTRAINT "friend_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "profile_id" SET DATA TYPE BIGINT,
ALTER COLUMN "friend_profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "friend_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "friend_request" DROP CONSTRAINT "friend_request_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "user_profile_id" SET DATA TYPE BIGINT,
ALTER COLUMN "friend_profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "friend_request_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "profile" DROP CONSTRAINT "profile_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "user_id" SET DATA TYPE BIGINT,
ALTER COLUMN "status_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "room" ALTER COLUMN "master_profile_id" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "room_channel" DROP CONSTRAINT "room_channel_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "room_channel_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "room_join_code" DROP CONSTRAINT "room_join_code_pkey",
ALTER COLUMN "author_profile_id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "room_join_code_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "room_message" DROP CONSTRAINT "room_message_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "profile_id" SET DATA TYPE BIGINT,
ALTER COLUMN "room_channel_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "room_message_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "room_participant" DROP CONSTRAINT "room_participant_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "user_profile_id" SET DATA TYPE BIGINT,
ADD CONSTRAINT "room_participant_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "user" DROP CONSTRAINT "user_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "user_profile_status" DROP CONSTRAINT "user_profile_status_pkey",
ALTER COLUMN "user_id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE BIGINT,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "user_profile_status_pkey" PRIMARY KEY ("id");

-- AddForeignKey
ALTER TABLE "profile" ADD CONSTRAINT "profile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_profile_status" ADD CONSTRAINT "user_profile_status_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "filter_user" ADD CONSTRAINT "filter_user_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "filter_user" ADD CONSTRAINT "filter_user_filter_profile_id_fkey" FOREIGN KEY ("filter_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "friend" ADD CONSTRAINT "friend_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "friend" ADD CONSTRAINT "friend_friend_profile_id_fkey" FOREIGN KEY ("friend_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "friend_request" ADD CONSTRAINT "friend_request_user_profile_id_fkey" FOREIGN KEY ("user_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "friend_request" ADD CONSTRAINT "friend_request_friend_profile_id_fkey" FOREIGN KEY ("friend_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dm_participant" ADD CONSTRAINT "dm_participant_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dm_message" ADD CONSTRAINT "dm_message_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room" ADD CONSTRAINT "room_master_profile_id_fkey" FOREIGN KEY ("master_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room_join_code" ADD CONSTRAINT "room_join_code_author_profile_id_fkey" FOREIGN KEY ("author_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room_participant" ADD CONSTRAINT "room_participant_user_profile_id_fkey" FOREIGN KEY ("user_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room_message" ADD CONSTRAINT "room_message_room_channel_id_fkey" FOREIGN KEY ("room_channel_id") REFERENCES "room_channel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "room_message" ADD CONSTRAINT "room_message_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
